### ISSUE TITLE
Is there a way to ignore areas?

### ISSUE THREAD

**Issue by onesupercoder** [colmap/colmap#104]
This is really awesome and I admit I don't understand how it works.  And so I hope you could answer a newbie question.  Is it possible to reconstruct a 3D model from an object spinning with a fixed position camera?  Is there a setting that I could enable to ignore the floor or surrounding area that is fixed while the object spins?

**Comment by xiaofeiwu** [comment]
This should be possible by removing the features located in the area you would like to ignore.

**Comment by ahojnnes** [comment]
Sorry for the late reply but I somehow missed this issue.

As @xiaofeiwu mentions, this could be achieved by manually removing features on the background or you could make all background areas black before feature extraction.

Hope it helps, let me know if you have other questions.

**Comment by sungh66** [comment]
@ahojnnes I also tried to reconstruct a clean dense point cloud of the object to obtain the object scale information. The background needed to be removed during dense reconstruction, rather than at feature matching (because of possible impact on pose accuracy). We used colmap patch_match_stereo \
--workspace_path path/to/dense/workspace \
--PatchMatchStereo.depth_min $MIN_DEPTH \
--PatchMatchStereo.depth_max $MAX_DEPTH
depth_min and depth_max are used as the threshold to filter out the depth of the target object, but the fused ply of dense reconstruction is still unchanged, we have the target object and background binary mask to help find the depth threshold range, do not know whether our understanding is correct, how should we solve this problem？
