### ISSUE TITLE
Reduced point location precision after geo-registration

### ISSUE THREAD

**Issue by WennPaper** [colmap/colmap#1088]
I encountered the exact same issue as mentioned in https://github.com/colmap/colmap/issues/711 where points in a point cloud lose their location precisions and merge into stripes after geo-registration:
![Untitled](https://user-images.githubusercontent.com/67032259/103487428-64d43880-4dd3-11eb-8055-85e4e79d8828.png)
I'm using the COLMAP 3.6 executable on Windows so I can't really modify codes. I wonder whether there is a solution to this issue. Thanks for any help in advance!

**Comment by tsattler** [comment]
Are you using binary output files (sparse reconstruction, dense reconstruction)? Or do you use the text output?

**Comment by WenTheProgrammer** [comment]
I have tried both bin and txt outputs for both sparse and dense model. For dense model I needed to replace cameras.bin/txt and images.bin/txt with the ones from sparse model since they are empty. The output format did not make a difference and the geo-registered models always had the stripes.

**Comment by ahojnnes** [comment]
The issue could be with exporting to PLY, which I assume you do, because the screenshot is from Meshlab. Do you do this conversion from within COLMAP? COLMAP uses single-precision for this step, which could potentially lead to these artifacts as well, if the numbers are very large.

**Comment by WenTheProgrammer** [comment]
Yes I did export the models in PLY format using COLMAP. However here is what I just tried: I geo-registered a point cloud using the command-line interface of COLMAP, and the geo-registered model was automatically saved in binary format. Then I loaded the geo-registered model using the graphical user interface of COLMAP, and exported it in text format. I modified the points3D.txt so that it only has six columns left including xyzrgb, and then I opened the modified points3D.txt with Meshlab and I still got the stripes:
![Untitled](https://user-images.githubusercontent.com/67032259/104855267-bbfd0180-58d9-11eb-8c0b-91ef18b9a64d.png)

**Comment by WennPaper** [comment]
Late comment, I think the issue was actually on the point cloud viewing software MeshLab, which cannot display point clouds with UTM coordinates properly since the coordinate values are too large. By normalizing the point cloud coordinates such as subtracting the mean for each axis would solve the problem.
