### ISSUE TITLE
Register a new image to the existing reconstruction with known camera intrinsic. 

### ISSUE THREAD

**Issue by letatanu** [colmap/colmap#1127]
I already have the reconstruction. Now, I want to register a new image to that one with a fixed camera intrinsic. 
I follow the steps as below:

> colmap feature_extractor 
>                     --database_path
>                     --image_path
>                     --image_list_path 
>                     --ImageReader.single_camera 1 
>                     --ImageReader.camera_params
>                     --ImageReader.camera_model 
> colmap exhaustive_matcher
>                         --database_path
>                         --SiftMatching.guided_matching 1
> colmap image_registrator
>                     --database_path 
>                     --input_path 
>                     --output_path

However, when I check for the camera intrinsic of the new registered image, it is different from the camera intrinsic which I input. I wonder whether `exhaustive_matcher` or `image_registrator` will re-estimate the camera intrinsic for the new image. I will appreciate it if you can suggest to me other ways to fix the camera intrinsic for the registration. Thank you.

**Comment by tdegraaff** [comment]
Try using `--Mapper.ba_refine_focal_length 0` and `--Mapper.ba_refine_extra_params 0` for `colmap image_registrator` to keep the prior intrinsics fix.

**Comment by letatanu** [comment]
Thank you @tdegraaff. It works.

**Comment by tdegraaff** [comment]
What would be the point of doing this? When registering a new image and keeping the given intrinsics, you will get the pose (+ 2D points) for the new image in `images.bin` and the 3D points for that image in `points3d.bin`. The prior `points3d.bin` file from your existing reconstruction in `input_path` should not be altered, the new files are stored in `output_path`. So if you are not interested in the new `points3d.bin` file, simply don't use it, right?

**Comment by saisharathsadu** [comment]
I got your point. When the case of using camera poses from the new path and my points3d.bin from older path, will they bothe have same co-ordinate system? Asking this beacuse if the image_registrator alters points3d.bin, will it indicates a local_bundle_adjustment happening?

**Comment by saisharathsadu** [comment]
Ok. But may be a silly question, when I do colmap image_registrator -h , I see option of bundle adjustment with some values in braces. Are those the default values or max values? Any idea on this notation of colmap?

**Comment by tdegraaff** [comment]
No, definitely not a stupid question, since this can be quite confusing.
As you can see in the implementation of the `image_registrator` command [link](https://github.com/colmap/colmap/blob/main/src/colmap/exe/image.cc#L237), it internally uses an `IncrementalMapper`, which is capable of performing bundle adjustment etc.. Therefore, the `image_registrator` also adds all the possible options of the `mapper` command, even though it uses only a subset of the functionality. It basically calls `IncrementalMapper::RegisterNextImage` [link](https://github.com/colmap/colmap/blob/main/src/colmap/sfm/incremental_mapper.cc#L216) sequentially for all the images. And this function then searches for 2D-3D correspondences, estimates the absolute pose of the camera and performs a refinement step (for which the parameters in the original answer disable the refinement of the intrinsics). No bundle adjustment is called there, thus I assume the docs to be correct.

To be 100% sure, you could call the `image_registrator` and use the `.txt` output formats, so that you can easily compare the `points3d.txt` before and after, so that you can see, whether the previous points changed.
