### ISSUE TITLE
Colmap changes focal length, even if `prior_focal_length=1`

### ISSUE THREAD

**Issue by SamDM** [colmap/colmap#1130]
**Describe the bug**
Colmap changes focal length during the `mapping` phase, even if `prior_focal_length=1` in the database.

**To Reproduce**
1. Edit the camera database: set prior parameters and set `prior_focal_length` to 1 for some cameras.
   
![image](https://user-images.githubusercontent.com/11174777/108880112-4126b500-7602-11eb-8506-6451c5a4e45a.png)

2. Click on feature extraction (wait), then feature matching (wait), then reconstruction (wait). Once cameras start to appear in the view window, double-click a camera.

![edited](https://user-images.githubusercontent.com/11174777/108882760-0b370000-7605-11eb-9a4c-39c9d3c20339.png)

3. Notice how the focal lengths for camera 7 are now around 1800 instead of around 680. Even though `prior_focal_length=1`, which should tell colmap to not change the focal lengths.

**Expected behavior**
Focal lengths remain unchanged when `prior_focal_length=1`.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS x86_64
 - COLMAP: 3.7 (Commit c08d6e2 on 2021-01-04 with CUDA)

**Comment by tsattler** [comment]
Looking at the code, this is expected behavior and not a bug. `prior_focal_length` just tells Colmap that the intrinsics for this camera are reasonably good and can be used for relative or absolute pose estimation without the need to calibrate the camera during these processes. It is not fixing the focal length of the cameras with `prior_focal_length = 1` during bundle adjustment. There are flags not to update the intrinsics and radial distortion parameters during bundle adjustment, but this applies to all cameras, not just selected ones.

**Comment by SamDM** [comment]
Too bad, that is what I was afraid of. As a current workaround I can try to:
1. Run sparse reconstruction once allowing colmap to refine the camera parameters.
2. Run again with all camera parameters fixed. Here I use
    - parameters from the first run (for the cameras where I didn't have intrinsic params already).
    - parameters from an external calibration (for the cameras where I have this info, e.i. where I had set `prior_focal_length=1` before).
