### ISSUE TITLE
does colmap support 2d image stitching

### ISSUE THREAD

**Issue by AprilCat** [colmap/colmap#1222]
now i need stitching many small picture to a big picture,and there is 20%~20% overlay between these small pictures. the overlay rate is not fixed. 
can i use colmap to stitching this kind of pictures? thanks...

**Comment by tsattler** [comment]
No, Colmap cannot stitch images together into a new image. There should be plenty of tutorials on how to do this with either the OpenCV or the VLFeat library.

**Comment by ishipachev** [comment]
@AprilCat 
COLMAP can be used as the source of relative positions and camera's intrinsics. After some parameters transformation you will be able to feed into some stitching software. For an example [PTGui](https://www.ptgui.com/) can do some additional post-processing stitching steps and parameters optimizations
But it requires some manual work or additional scripting, because PTGui and many others stiching SW prefer to work with ZYX angle (roll-pitch-yaw) and also uses _a, b, c_ parameters. Which can be extracted from COLMAP's camera coefficients:
https://www.panotools.org/dersch/barrel/barrel.html

So I would say -- its doable, but some additional scripts should be written.
