### ISSUE TITLE
Coordinate system used in Reconstruction?

### ISSUE THREAD

**Issue by Helaly96** [colmap/colmap#1229]
To what system are the Quaternions and Translation referenced to?

My problem is: I divided the scene into multiple sets of images, Scene1 (0-100), Scene 2 (110-150) and so on.

Colmap outputs for each image in each scene , the Quaternions and Translations.
so i thought i would stetch the model via a python script (by re-triangulating the points, moving the systems, etc..)

but to my surprise, the rotations and translation of Scene 1 are not in reference to the first frame, i thought the first frame would have no rotation and no translation and all images of the same scene would be referenced to it, however that's not the case.

so i was wondering, to what system exactly are those values related to?

**Comment by tsattler** [comment]
Structure-from-Motion systems such as Colmap can only reconstruct the scene up to an arbitrary similarity transformation, (rotating, translating, and scaling the scene does not change the reprojection errors).
As part of bundle adjustment, the origin of the coordinate system can drift away from the coordinate system of the first image registered (there is, I believe, an issue (either still open or closed) that discusses this).

**Comment by whuaegeanse** [comment]
@ahojnnes @tsattler @Helaly96 
Colmap treats the coordinate system of the first image registered as sptial coordinate reference in the beginning of SfM.
After the process of bundle adjustment，the poses of all images in the reconstrction would be changed.  It means that the coordinate system of the reconstruction does not change, while the poses of images in the reconstruction change because of doing bundle adjustment.
Colmap fixs the pose of first image registered  in the reconstrction when doing global bundle adjustment. However, the pose of first image registered may be changed when doing local bundle adjustment. So there may be a bug in local bundle adjustment of Colmap.  The pose of first image registered  in the reconstrction should be fixed all the time.
In addition, Colmap will perform scene regularization after each global bundle adjustment. This will cause the coordinate origin and scale of reconstruction to change.

**Comment by ahojnnes** [comment]
@whuaegeanse That's not an accurate description of what local BA does in COLMAP. Please refer to the implementation at: https://github.com/colmap/colmap/blob/dev/src/sfm/incremental_mapper.cc#L606
