### ISSUE TITLE
Change camera model after reconstruction

### ISSUE THREAD

**Issue by melhashash** [colmap/colmap#1292]
Hello, 

I wonder if it is possible to change the camera model after reconstruction and do BA only with the new parameters.

Also, is it possible to change the camera model after the feature extraction part?

Thanks!

**Comment by tsattler** [comment]
Yes, it is possible to change the camera model afterwards (you could just edit the cameras.txt file of the reconstruction if you export it in text format rather than binary format). Afterwards, you could run a bundle adjustment over all intrinsics and extrinsics (or adapt the code to only optimize what you want to optimize).

Yes, changing the camera model after feature extraction is possible, e.g., in the gui.

**Comment by melhashash** [comment]
@tsattler Thanks for your reply.
