### ISSUE TITLE
Bug report for the bitmap reader at util/bitmap.h

### ISSUE THREAD

**Issue by B1ueber2y** [colmap/colmap#1316]
Thanks for the amazing project!

For some image files, the Bitmap class defined at ``util/bitmap.h`` can wrongly import the image arrays with transposed dimensions, which results in many unexpected errors. e.g. The dimensions will be unmatched for image undistorter (might be the cause for #253). The bugs are reproduced across two linux desktops: one with ubuntu16.04 and another with ubuntu18.04.

I attach 20 sample images on [google drive](https://drive.google.com/file/d/1eonftYh12qi-j2K5vc-1Zg8qpBi1puCp/view?usp=sharing) to reproduce the error, all of which have this problem. For the Dubrovnik city in the BigSFM project, there are 247 out of 6844 images suffering from this issue.

**Solution:** Using opencv to read and re-write out the image file can resolve the problem. I guess Freeimage is not supporting some messed up image headers. 

Code for reproducing the errors for those images can be scripted as below:
```
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/eigen.h>
#include <pybind11/stl_bind.h>
#include <colmap/util/bitmap.h>
namespace py = pybind11;

void bind_module(py::module& m) {
py::class_<colmap::Bitmap>(m, "COLMAP_Bitmap")
        .def(py::init<>())
        .def("Read", &colmap::Bitmap::Read)
        .def("Write", &colmap::Bitmap::Write)
        .def("Width", &colmap::Bitmap::Width)
        .def("Height", &colmap::Bitmap::Height)
        .def("Channels", &colmap::Bitmap::Channels);
}
```
```
import cv2
fname = "12710583@N02_2431287195.jpg"
# opencv
img = cv2.imread(fname)
print(img.shape)
# colmap
bitmap = COLMAP_Bitmap()
bitmap.Read(fname, True)
print(bitmap.Height(), bitmap.Width())
pdb.set_trace()
```

Results:
(2000, 1500, 3)
1500, 2000

By looking up the actual image the shape from opencv is correct.

**Comment by ferreram** [comment]
Hey @ahojnnes ,
I am not really fond of this change. While I agree that not applying the orientation specified in the EXIF will cause confusion to the unaware user, IMHO it does not make sense to apply it in Colmap. This information is given for users convenience so that viewers display images as they have shot it with their cameras but in Colmap we care about geometry and if we follow the EXIF orientation we can end up with different cameras configuration whereas the images have been taken with exactly the same camera and hence can share their intrinsics and distortion parameters.  This last point seems more important to me (sharing the same calibration) that any user convenience related issue.

**Comment by ahojnnes** [comment]
@ferreram I agree this wasn't a particularly smart change. I was rushing too much with this change without giving it a proper thought. Would you have cycles to disable this by default?

**Comment by ferreram** [comment]
Yeah sure.  I'll take care of it this week.

**Comment by ahojnnes** [comment]
Thanks so much!
