### ISSUE TITLE
Mapper with pba not using GPU

### ISSUE THREAD

**Issue by djc26** [colmap/colmap#1359]
I am running colmap mapper from the command line with the flag 
"--Mapper.ba_global_use_pba 1"

It does run marginally faster than without the flag, but I do not see any gpu utilization (as reported by nvidia-smi). I believe colmap is correctly configured to use the gpu since I see significant  gpu utilization during feature extraction and mapping. I am on Ubuntu 20.04.

Thanks for your help!

**Comment by tsattler** [comment]
Looking at the code (https://github.com/colmap/colmap/blob/dev/src/optim/bundle_adjustment.cc#L583), it seems Colmap switches to the CPU implementation provided by PBA once the bundle adjustment problem is large enough. This seems to be done to ensure that the problem can be solved reliably as the GPU implementation (in my understanding) supports only single precision.

**Comment by djc26** [comment]
Thanks for the tip! I went ahead and removed this check and rebuilt the project.  I'm still not seeing usage of the GPU though.

Is there a difference in the output I should see when using PBA? I tried adding a PrintHeading1 in the if/else but I don't see this message get printed to the console.

**Comment by tsattler** [comment]
PBA is only available under certain conditions: "If all your images use the SIMPLE_RADIAL camera model (default) without shared intrinsics, you can use PBA [wu11] instead of Ceres Solver [ceres] for fast bundle adjustment, which can be activated in the reconstruction options under the bundle adjustment section (use_pba=true)." (from https://colmap.github.io/tutorial.html#sparse-reconstruction). Do these hold for your scenario?

**Comment by djc26** [comment]
Ah my problem uses shared intrinsics. Thank you very much for your help and sharing this resource with me!
