### ISSUE TITLE
colmap sequential_matcher error

### ISSUE THREAD

**Issue by LuisaoStuff** [colmap/colmap#1453]
**Describe the bug**
Hi I'm using the github project [instant-ngp](https://github.com/NVlabs/instant-ngp) which has [this script](https://raw.githubusercontent.com/NVlabs/instant-ngp/master/scripts/colmap2nerf.py). I have installed all dependencies as the README.md says. But I keep getting the following error when it executes the command `colmap sequential_matcher --SiftMatching.guided_matching=true --database_path colmap.db`:

**Error**
```
==== running: colmap sequential_matcher --SiftMatching.guided_matching=true --database_path colmap.db
F0308 15:19:33.656744  5253 opengl_utils.cc:56] Check failed: context_.create() 
*** Check failure stack trace: ***
    @     0x7f3f5dfa01c3  google::LogMessage::Fail()
    @     0x7f3f5dfa525b  google::LogMessage::SendToLog()
    @     0x7f3f5df9febf  google::LogMessage::Flush()
    @     0x7f3f5dfa06ef  google::LogMessageFatal::~LogMessageFatal()
    @     0x56168606730c  colmap::OpenGLContextManager::OpenGLContextManager()
    @     0x561685f75174  colmap::SiftGPUFeatureMatcher::SiftGPUFeatureMatcher()
    @     0x561685f759f4  colmap::SiftFeatureMatcher::SiftFeatureMatcher()
    @     0x561685f76a48  colmap::SequentialFeatureMatcher::SequentialFeatureMatcher()
    @     0x561685e6ab6f  RunSequentialMatcher()
    @     0x561685e55eaf  main
    @     0x7f3f5c3a00b3  __libc_start_main
    @     0x561685e59f6e  _start
Aborted (core dumped)
FATAL: command failed
```

**Expected behavior**

It should generate a json file.

**Server:**
 - OS: **Ubuntu 20.04** (Upgraded from 18.04)
 - Deep Learning AMI (Ubuntu 18.04) Version 57.0
 - EC2 instance type **g4dn.2xlarge**

**Comment by tsattler** [comment]
When you are not using cuda (needs to be specified during compilation) but specify that the GPU should be used during matching (flag `--SiftMatching.use_gpu 1`, which is enabled by default), Colmap is trying to create the OpenGL context for the OpenGL-based feature matcher via the Qt library. Since you are running Colmap on a server without an attached display, I'd assume that creating the context fails for this reason.

Possible solutions are to either use a cuda-enabled version of Colmap (assuming that the server provides you with access to an NVidia GPU) or to do matching on the GPU.

**Comment by LuisaoStuff** [comment]
I set the flag `--SiftMatching.use_gpu 0` and it worked! Thanks :)
