### ISSUE TITLE
Image Exif Rotation is not properly used in some images.

### ISSUE THREAD

**Issue by tompollok** [colmap/colmap#1456]
I took Photos (JPG) using a Nikon Z6 and reconstructed them using COLMAP. My 90° rotated images are not properly rotated when importing them with COLMAP, while reading them with OPENCV the images are properly rotated.

I thought #1318 would adress this issue. If it helps, I could send an example image.

**Comment by ferreram** [comment]
This behavior has been removed in #1406 because in structure-from-motion what we care about is geometry.  If the Exif rotation is used we can end up with different camera's intrinsics because the images are not in the same orientation whereas the images have been taken with the same camera in the same conditions.  Note also that using the Exif rotation will not improve any step of Colmap at all.

**Comment by tompollok** [comment]
That makes sense. I was just assuming that EXIF rotation was now used for the 3.7 release, when I saw the EXIF PR, but didn’t realized that another PR reverted that. Thank you very much for your fast reply.

**Comment by tsattler** [comment]
Actually, automatically orienting the images based on the rotation stored in the Exif tag can help as you can use upright features instead of features that are invariant to in-plane orientations. The former are typically more powerful. However, you can also just prerotate your images using the command line tools of the ImageMagick library.

**Comment by tompollok** [comment]
Thank you for the hint with the upright features.
