### ISSUE TITLE
Point to image correspondance for dense reconstruction 

### ISSUE THREAD

**Issue by fclairec** [colmap/colmap#1527]
Hi,

I am looking for the image IDs used for the reconstruction of each point in the dense point cloud. So basically similar as in points3d.txt but for the dense point cloud. To the best of my knowledge this information is not printed unless it is in the consistency graph (?). 

If so, I missed it because I am not able to process the consistency graph files. Could you advise me on how to read them: X.geometric.bin and X.photometric.bin (in my case 1KB large and seemlingly empty)? The documentation says > <row><col><N><image_idx1>...<image_idxN>. However I don't seem to find this structure in the files. 

If my request is not solvable with the information contained in the consistency graph, might I ask for a possibility to develop this? With some pointers I might be able to contribute.

A similar issue was raised in 2019 (https://github.com/colmap/colmap/issues/762) but I can't seem to contact the participants of the discussion back then. 

Thank you.

**Comment by tsattler** [comment]
Sorry for not replying to you in the other issue. I currently have very limited time due to deadlines.

If you are interested in which 3D points in the fused point cloud (obtained by `stereo_fusion`), this information is stored in the `.vis` file that is generated (see https://github.com/colmap/colmap/blob/dev/src/exe/mvs.cc#L215 and https://github.com/colmap/colmap/blob/dev/src/mvs/fusion.h#L171).

**Comment by shubham-monarch** [comment]
> oh, I missed this. Thanks a lot for your reply! :)

where can I find the .vis file?

**Comment by shubham-monarch** [comment]
As per my understanding, the .vis file won't be generated if we use the .BIN format during the stereo_fusion step. How do we use the consistency_graph data then?
