### ISSUE TITLE
Geo registration failed

### ISSUE THREAD

**Issue by mrKornWij** [colmap/colmap#1643]
I use "colmap align -- " command but it occurs an error in the picture below. how to solve this? 
![colmaperrorask](https://user-images.githubusercontent.com/88375996/193022661-660337fa-c0a3-4406-ab1a-ae2b07752505.png)

**Comment by tsattler** [comment]
As stated by the error message, the file `/sfm_superpoint+superglue/geo-registered/given_positions.txt` cannot be opened. I guess you mean `sfm_superpoint+superglue/geo-registered/given_positions.txt`?

**Comment by mrKornWij** [comment]
@tsattler  thanks a lot,  after put known position xyz of several images. all images in model will be aligned to the same scale right?
then, the next question is I select emu as an alignment type. and I choose first image to be at (0,0,0) then GUI show the image(0,0,0) at the origin of GUI. Is that correct?

**Comment by tsattler** [comment]
The `model_aligner` scales, rotates, and translates the reconstruction such as to best align to the specified camera positions. Thus, all image positions in the 3D model will be scaled by the same factor.

Due to noise, it is unlikely that there is a transformation that perfectly aligns the image positions in the 3D model to the positions in the text files. It is thus not guaranteed that the first image will be at exactly (0, 0, 0) after the transformation.

**Comment by mrKornWij** [comment]
Clearly understand.Thank you so much
