### ISSUE TITLE
some questions about Reconstruct sparse/dense model from known camera poses 

### ISSUE THREAD

**Issue by daekyounglee** [colmap/colmap#1710]
Hi, I have some questions about 'Reconstruct sparse/dense model from known camera poses' in the documentation.

1. I used only 1 camera for image, so I wrote cameras.txt like this:
![Screenshot from 2022-12-01 19-56-36](https://user-images.githubusercontent.com/102590177/205035838-b2325951-fc1e-413f-9a7a-9f48873d89c3.png)
And images.txt like this:
![Screenshot from 2022-12-01 19-59-39](https://user-images.githubusercontent.com/102590177/205036173-93144bf8-6ed3-45be-bbe2-cc46ec016297.png)
However, when I run **colmap feature_extractor**, colmap found 1 camera per image, total 184 cameras. Do you know why this happened?

2. I ran **colmap feature_extractor**,**colmap exhaustive_matcher**, **colmap point_triangulator**  and got bin files as a result. Is this the final ouput file of reconstructed sparse model? I thought the calculated results such as 3D points should be written in points3D.txt. However I opened the points3D.txt, it was empty. 

3. I wonder if there is a way to see the camera's path of reconstructed sparse model from the command line to the gui.

**Comment by tsattler** [comment]
1. Per default, and unless specified otherwise, the `feature_extractor`creates one camera per image. During the `point_triangulator`, these cameras will be ignored and only the ones in the input file are used.
2. The default output of colmap (both the `mapper` and the `point_triangulator`) are outputting `.bin` files. If you want to have `.txt` files, you can use the `model_converter` to convert the `.bin` files to `.txt` files.
3. I don't understand the question.
