### ISSUE TITLE
Why pba is Remove in latest update? 

### ISSUE THREAD

**Issue by 519174419** [colmap/colmap#1865]
Why pba is Remove in latest update ? Is it useful to accurate the sparse reconstrucion?

**Comment by ahojnnes** [comment]
PBA is incompatible with latest CUDA 12 and newer due to deprecated CUDA API usage. The effort to upgrade it would be very high. Given the fact that PBA has limitations in terms of not supporting shared intrinisics, etc. and the fact that Ceres has significantly gained in speed (and CUDA support is coming as well), I decided to drop support for PBA and thus reduce maintenance burden going forward.
