### ISSUE TITLE
Implement masking of images in feature extraction

### ISSUE THREAD

**Issue by ahojnnes** [colmap/colmap#208]

**Comment by insikk** [comment]
I think this is really necessary feature when we want to construct 3d model of an object from photos taken with variety of background. 

@ahojnnes  I am trying to get 3d model of can from below images. I thinking manually masking out background may give me the 3d model. However, is there better way to achieve it with COLMAP software without mask? At least, can you give me some related papers so I can study it by myself?
![image](https://user-images.githubusercontent.com/2110359/33604004-d24abcac-d9f7-11e7-8cd4-2990076fdb12.png)

**Comment by spriglet66** [comment]
This feature would be so useful! Is there a temporary work around like rubbing out the areas that I don't want colmap to identify as features such as; moving cars or people? Maybe deleting the areas in photoshop and saving as a png with alpha transparency then importing that into colmap?

Thanks!

Ross.

**Comment by ahojnnes** [comment]
Hi, since there is growing interest in this feature, I am planning to implement this soon. Before starting, I would like to get some feedback to the following questions:
1) Is your final goal a sparse 3D reconstruction?
2) Is your final goal dense depth/normal maps?
3) Is your final goal a dense 3D reconstruction (point cloud or mesh)?
Please answer with 1), 2), 3), or a combination of them.

**Comment by insikk** [comment]
@ahojnnes Thank you. I am planning to reconstruct sparse 3D only. 
By the way, what I want to know is that if there is some method to do SfM when we do not have explicit mask. Your experience in SfM may suggest us some research paper on this topic. 

With explicit mask, I was able to generate sparse 3d model. In this case, I was very luck that the dataset I used already contains ground-truth mask for target object. However, it is really rare case. 
![image](https://user-images.githubusercontent.com/2110359/34197719-015a9d1e-e5ab-11e7-8bea-64a25751af8d.png)
![image](https://user-images.githubusercontent.com/2110359/34197722-06295218-e5ab-11e7-96c5-fc06bbebdb65.png)

@spriglet66 If you have ground truth mask, then just use opencv to mask out background. 
For me, just masking out background was not enough, so I had to crop so the object fit in whole image as you can see in the above image.

**Comment by ahojnnes** [comment]
Typically it would be better to also use the background as well for the reconstruction in the sparse stage. Only afterwards you would prune out features in the background as a post processing step. The reasoning for this is that you want to use as many constraints as possible spread over the entire image to get a precise camera calibration. Maybe you can explain your setup in more detail and I can give some better advice.

**Comment by spriglet66** [comment]
Hi Thanks for the swift reply! 
My goal is a combination of 1 + 2 + 3 to achieve a mesh. My application usage of colmap (which may be be useful for you to know) is: Surveying buildings with an emphasis of speed of data capture i.e. minimal time on site.

My Steps to mesh creation are and the reason why a masking feature would be really great is as follows:

1) 360 Spherical Image capture of the building in question (The reason for using a 360 camera over normal rectilinear camera is that the amount of information i can record in one picture vs a normal camera image is massive.
2) The conversion of each spherical image into a cubic projection which will be accepted by colmap 
3) Input of the cube images into colmap and proceed with reconstruction as normal.
4) Final result = mesh from spherical input images where a huge amount of data can be recorded on site in virtually no time vs a normal camera.

The addition of the masking feature or even just the ability to delete certain features identidied in an image using the database manager would mean I can use my spherical images as input (seperate issue as currently not supported however i am able to send you my datasets so you could implement it) and be able to tell Colmap to not use the features recognized in the input images to reconstruct the point cloud. 

Objects within the input images which are a problem without the masking features are:

- Artifacts caused by me being in every image, as I am holding the camera and since it is a 360 camera i am in every shot.

- Artifacts caused by reflections in buildings i am trying to scan

- Artifacts caused by objects in the background moving e.g. Moving Cars and People (Very common issue in my area of usage.) 

 
I am aware of the branch by @daleydeng where he adds support for spherical equirectangular images as input however I would be extremely grateful if you could add the support for spherical equirectangular datasets as this completely cut out the need to convert my spherical images into a non distorted cube format which essentially multiplies the images I have to import to colmap for it to process by 6!

Thank you! 
Ross.

**Comment by ddewert** [comment]
Is there an algorithmic way to take images from a spherical camera as input, and label pixels that are parts of reflections on surfaces? For instance if I'm confused about whether I'm looking at a reflection I can usually make sense of what I'm seeing by moving my head a little bit. There's a paper on doing this with video out there somewhere.

**Comment by SBCV** [comment]
> Please answer with 1), 2), 3), or a combination of them.

 1 and 3

**Comment by rucativava** [comment]
Another option would be to allow the user to control a Bounding Box in the Sparse view, and only points that fell inside that box would get Dense compute....?

**Comment by odiseo123** [comment]
Hi @ahojnnes,
First of all kudos for this great tool.
 
Regarding this thread, the ability to associate a mask to the images would also be very useful for medical applications where the images have a constant region occluded by an eyepiece.

![example](https://user-images.githubusercontent.com/18690090/39497721-f2d8e782-4de7-11e8-9ff7-e2a768b71fd2.png)

The black contour can lead to false detection of features all around the edge. These features would appear static while the image content is actually changing, thus leading to errors early in the estimation pipeline.
I have tried the alternative of cropping the image (i.e. extracting the largest inscribed square in the contour). This improves results although with still some minor issues (add link). This approach however sacrifices a lot of image content which is quite valuable given the limited field of view of this particular setup.
![untitled 1](https://user-images.githubusercontent.com/18690090/39498382-2a3b1436-4deb-11e8-8586-868c9d9af59e.png)

Goal here will be option 3) or at least 1), i.e., a dense point cloud would be preferable but a sparse one is still valuable.

**Comment by goetzmoritz** [comment]
I'd like to reopen this and kindly ask how far the implementation is? I'd be interested in 1), 2) and 3) actually.

**Comment by ProGamerGov** [comment]
Would this feature let you use images like those that are created for things like Google Street View's 360 images? Those 360 images are made from multiple pictures taken as the person rotates around on the spot.

**Comment by ryanismert** [comment]
I'm interested in 1, 2, 3.

In our case, we want to mask out certain known moving objects, like people.

**Comment by mgprt** [comment]
@ahojnnes I can prepare a pull request to filter out image features after extraction. This should help in cases when there are static parts in the images that affect feature matching and relative pose estimation.
We should first discuss some technical details, though.

**Comment by puzzlepaint** [comment]
I had some code for masking extracted features (this addresses point 1 only) and made a PR for it now: #522

**Comment by ahojnnes** [comment]
@puzzlepaint's implementation has been merged. Please refer to https://colmap.github.io/faq.html#mask-image-regions for basic documentation.

**Comment by dnzzcn** [comment]
> @puzzlepaint's implementation has been merged. Please refer to https://colmap.github.io/faq.html#mask-image-regions for basic documentation.

Hi, I have been trying image masking but the command line argument '--mask_path' is not recognized by automatic_reconstructor of colmap. Do you know why this my be happening?

**Comment by puzzlepaint** [comment]
* Do you use a sufficiently recent version of the program? I believe that this is not currently available in the master branch, only dev.
* I think that the options are actually called `--ImageReader.mask_path` and `--ImageReader.camera_mask_path` and are only available for manual feature extraction via `colmap feature_extractor [...]`, not for automatic_reconstructor.

**Comment by dnzzcn** [comment]
>     * Do you use a sufficiently recent version of the program? I believe that this is not currently available in the master branch, only dev.
> 
>     * I think that the options are actually called `--ImageReader.mask_path` and `--ImageReader.camera_mask_path` and are only available for manual feature extraction via `colmap feature_extractor [...]`, not for automatic_reconstructor.

Both of your arguments make total sense thank you.

**Comment by thunders82** [comment]
Hi,

I've attached a patch that will allow you to use mask_path with the automatic reconstruction. Works with the gui or the command line : 
[file0001.patch.txt](https://github.com/colmap/colmap/files/3432547/file0001.patch.txt)

Cheers,

Geoffrey.

**Comment by isht7** [comment]
using `--ImageReader.mask_path`, I am able to mask moving objects during sparse reconstruction. Is it possible to also remove these objects during dense reconstruction(stereo_fusion)?

**Comment by kwea123** [comment]
Then what is the use of `camera_mask_path`? What is the difference between `mask_path`?

**Comment by isht7** [comment]
I believe they are the same thing but `camera_mask_path` takes one mask file and applies to all image files. But `mask_path` takes a folder and applies to each individual input image file.

**Comment by kwea123** [comment]
@isht7 Thanks for clarifying. It makes sense.

**Comment by caligraf1** [comment]
> @puzzlepaint's implementation has been merged. Please refer to https://colmap.github.io/faq.html#mask-image-regions for basic documentation.

Is it implemented just for the feature extraction phase or also for the 3d dense point cloud reconstruction? Also, does it work in all versions?
