### ISSUE TITLE
Question regarding CMake build and colmap executable linked libraries

### ISSUE THREAD

**Issue by abhiagg92** [colmap/colmap#2206]
I have a question regarding the CMake build and how the libraries are linked to the `colmap_main` executable. I am using the main branch (0d9ab40) and am able to successfully build the project. However, I found one peculiar issue while going through the dependencies of the `colmap_main` executable. As per the `src/colmap/exe/CMakeLists.txt` file, we are linking only four libraries i.e.

- colmap_controllers
- colmap_scene
- colmap_sfm
- colmap_util

But while going through the source files used while creating the `colmap_main` target, I saw that `colmap/retrieval/visual_index.h` header file is included in `vocab_tree.cc` file. The above-mentioned header file is used while creating the `colmap_retrieval` library which is only linked to `colmap_controllers` library as a private library. So `colmap_main` should not have access to `colmap_retrieval` library via `colmap_controllers` library. So could someone please tell me how `colmap_main` gets the information about `visual_index.h` header file? Is my understanding correct or am I missing something here?

**Comment by ahojnnes** [comment]
Thanks, according to latest commits, colmap_main links to colmap_retrieval. Maybe this was not the case before in the commit that you look at now. In this case, an include can still work, as visual_index.h shares the same root include directly as the other libraries. Note that CMake, by default, is not sophisticated enough to prevent individual headers from being included, if they are not linked. This is different from e.g. bazel or buck that more strictly layer the include directories to prevent this issue. Since visual_index.h is a header-only library, you also don't see missing symbols during the linking step. I hope this explains it.
