### ISSUE TITLE
TriangulateOptimalPoint fails to pass the test!

### ISSUE THREAD

**Issue by RayShark0605** [colmap/colmap#2209]
**Describe the bug**
"TriangulateOptimalPoint fails to pass the test!"
The issue seems to be that the point triangulated by TriangulateOptimalPoint has too much error, or is even incorrect! Therefore, I sincerely ask: Is there a problem with the TriangulateOptimalPoint method?"

**To Reproduce**
1. Go to "src\colmap\geometry\triangulation_test.cc"
2. change the "TriangulatePoint" method to "TriangulateOptimalPoint" in line 63

**Expected behavior**
an error at line 68 with EXPECT_TRUE.

**Screenshots**
![image](https://github.com/colmap/colmap/assets/66742177/e7ba0216-2ea7-4d75-9840-eecc225ee182)

**Environment:**
 - OS: Windows 11

**Comment by ahojnnes** [comment]
Yes, I can confirm that the current implementation fails to pass the tests. This may be a bug or an issue with the setup of the test that conflicts with some assumptions of the Lindstrom method. It has been a long time since I implemented this and I had a brief look at the paper again but don't see an obvious bug. Since this function is not used anywhere within colmap, I am inclined to just remove the code.

**Comment by RayShark0605** [comment]
Thanks for the reply~

**Comment by jinhwanlazy** [comment]
@ahojnnes May I ask why it isn't used anymore? I just stumbled upon the debate between midpoint triangulation and optimal triangulation, and in my naive understanding, optimal triangulation appears to be superior.
