### ISSUE TITLE
colmap3.9.1 + pycolmap 0.5 not working with Hloc and PixSFM

### ISSUE THREAD

**Issue by shubham-monarch** [colmap/colmap#2387]
I am currently using [PixSFM](https://github.com/cvg/pixel-perfect-sfm) to perform 3D reconstruction. Everything was working fine when I was using a combination of `COLMAP 3.8` and `pycolmap 0.4`. After making the update to `COLMAP 3.9.1` and `pycolmap 0.5`, `sfm.reconstruction` function is throwing errors mostly because no model was generated. 

I understand that [HLoc](https://github.com/cvg/Hierarchical-Localization) currently supports `pycolmap <= v0.4` and `COLMAP 3.8`. However, there are certain functionalaties of `COLMAP 3.9.1` and `pycolmap 0.5` that I need for the project that I am working upon. 

I was wondering if there's something in particular I might have overlooked while making the `COLMAP + pycolmap` update. 

I would be happy to be furnish more details (code/logs) if needed.

**Comment by ichsan2895** [comment]
From my experience, we must compile from source `ceres-solver-2.1.0`.
The problem is **newer** Ubuntu (> 23.10) uses `ceres-solver-2.2.0`.

After you use `ceres-solver-2.1.0`, the rebuilt from source for `colmap 3.9.1`, `pyceres-v1.0`, and `pycolmap 0.4.0`. AFAIK it works. But `colmap 3.8` is recommended by the `pixsfm`'s developers.
