### ISSUE TITLE
[Question] Exhaustive feature matching

### ISSUE THREAD

**Issue by Ntweat** [colmap/colmap#246]
Hi

What algorithm does "Exhaustive feature matching" follow.

Thanks,

**Comment by pmoulon** [comment]
Matching all the pairs.
So if you consider all the possibility if gives you a matrix.
But since we can ignore the diagonal and we suppose that matching is symmetric we process only the upper or lower diagonal.

0 1 2 3 4
0
1
2
3
4

Please take a look to the exported svg files in the matching directory.
All the tested pairs are exported.:
- putatives
![putativeadjacencymatrix](https://user-images.githubusercontent.com/3235050/32919867-28886a68-cadc-11e7-87e9-18ac9c49f449.jpg)
- pair kept after geometric filtering 
![geometricadjacencymatrix](https://user-images.githubusercontent.com/3235050/32919866-28702e94-cadc-11e7-9fcd-d5df49475049.jpg)

You can also visualize that by using the adjacency matrix viewer:
https://github.com/openMVG/openMVG/issues/831

**Comment by Ntweat** [comment]
@pmoulon Thank you!

**Comment by ahojnnes** [comment]
The adjacency matrix view is called "match matrix" in COLMAP.

**Comment by Ntweat** [comment]
@ahojnnes which feature matching algorithm does COLMAP use?
Brute force? FLANN? 
Is there a paper I can refer?

**Comment by ahojnnes** [comment]
Which feature matching option did you use?

**Comment by Ntweat** [comment]
Default:  SIFT

**Comment by ahojnnes** [comment]
SIFT is a type of local feature but not a matching approach. Which option did you choose in the feature matching stage? Or did you use the automatic reconstruction tool?
