### ISSUE TITLE
Global Loop closure doesn't work?

### ISSUE THREAD

**Issue by zjcv2012** [colmap/colmap#254]
Hi, 
I was running sparse reconstruction from COLMAP on a dataset(fps=5, num_images=677, resolution: 1920x1080) collected by a smartphone(with known intrinsic) mounted in a car driving on the road(essentially the path is a rectangle).

I want to test the sequential matching with loop closure enabled(overlap=20, loop_detection_period=1, loop_detection_num_images=30 ), however, it seems that even the features are matched between images with visually similar images(not only the sequential image), the performance doesn't seem to be good. (comparing with result from orbslam, which also uses loop-closure technique).
COLMAP:
![result_colmap](https://user-images.githubusercontent.com/16794189/33440080-08988666-d5bd-11e7-82ca-e99d069f2b09.png)
ORB-SLAM:
![result_orbslam](https://user-images.githubusercontent.com/16794189/33440111-21e00cfc-d5bd-11e7-8ded-ee47663d95c6.png)

I am just wondering whether I can improve the loop closure performance of colmap, or it is very hard to have a global loop closure since it uses incremental SFM technique.

Thanks!

**Comment by ahojnnes** [comment]
Hi,

Try skipping frames, eg, use only a frame every 1 or 2 seconds. This should improve reduce drift for video data. You could also try to I crease the size of the local bundle adjustment window.  Otherwise, COLMAP probably detects the loops successfully but cannot optimize them as well as ORBSLAM, which is specifically optimized for the SLAM scenario. It also does pose graph optimization if I remember correctly, which is better in correcting for large drift than pure bundle adjustment used in COLMAP. 

Best,
Johannes

**Comment by ahojnnes** [comment]
Assuming my reply answered your question and closing. Feel free to reopen in case of additional questions.
