### ISSUE TITLE
Can the colmap vocab_tree_matcher accelerate

### ISSUE THREAD

**Issue by luocha0107** [colmap/colmap#2743]
For me, vocab_tree_matcher is a bit slow and doesn't meet the demand. I want to know if it's possible to do multithreading in parallel.
I test use  --SiftMatching.num_threads 4 and --SiftMatching.use_gpu 1
  --SiftMatching.gpu_index 0
But it doesn't seem to be working,what can I do to speed it up?

**Comment by ahojnnes** [comment]
If the indexing and search is too slow, it is usually caused by a large number of detected features per image. You can limit them by setting --VocabTreeMatching.max_num_features to e.g. 1000. This comes at an accuracy/recall tradeoff and you can tune the value based on your needs. It usually makes sense to combine vocabulary tree matching with a subsequent transitive matching to close triplets.

**Comment by luocha0107** [comment]
> If the indexing and search is too slow, it is usually caused by a large number of detected features per image. You can limit them by setting --VocabTreeMatching.max_num_features to e.g. 1000. This comes at an accuracy/recall tradeoff and you can tune the value based on your needs. It usually makes sense to combine vocabulary tree matching with a subsequent transitive matching to close triplets.

I tried what you said and generated a vocab tree for my photo library.Now,I want to do multi-threaded parallel computation on a single GPU for feature matching to improve speed, is this possible, Or multithreaded computation can only be done on multiple Gpus

**Comment by ahojnnes** [comment]
Multi-threaded CPU + multi-GPU should also help with vocab-tree matching.

**Comment by luocha0107** [comment]
> Multi-threaded CPU + multi-GPU should also help with vocab-tree matching.

OK,I only one GPU,it out of reach.
Thank you for reply.
