### ISSUE TITLE
Reconstruction failure (Commit 803852d on 2018-05-16 with CUDA)

### ISSUE THREAD

**Issue by mjkmoynihan** [colmap/colmap#366]
Following update to 3.4 automatic reconstruction(sparse) fails to accurately calculate camera positions. 
Using the same imageset (12 cameras, wide baseline) and default settings for feature extraction and matching, the reconstruction accuracy suffers hugely between version 3.3 and 3.4. 

Using Commit 803852d on 2018-05-16 with CUDA, on Ubuntu 16.04 LTS

**Comment by ahojnnes** [comment]
Can you share the images with me?

**Comment by mjkmoynihan** [comment]
Hi, 

the images are private so I've sent them to your inf.ethz.ch email address.

**Comment by ahojnnes** [comment]
I didn’t get a message from you so far.

**Comment by ahojnnes** [comment]
It is correct.

**Comment by ahojnnes** [comment]
Okay, it seems like the images you sent have quite some distortion and the features are clustered in small parts of the images. In this case, the reconstruction process is typically rather brittle and depends on the initialization. I guess, one of the dependencies or so changed some small parameter and that's why it reconstructed earlier. Is there any chance you can use fixed intrinsics during the capture?

**Comment by mjkmoynihan** [comment]
ok, thanks for looking into this. I can use fixed intrinsics in future. 
Is it possible to identify which dependency may have changed across versions such that we can return to automatically calculating the intrinsics in the future?

**Comment by ahojnnes** [comment]
It will be very hard to figure that out. I would guess, it has something to do with changes in Ceres-Solver or some of its dependencies.
