### ISSUE TITLE
COLMAP depthmap format is always smaller than input

### ISSUE THREAD

**Issue by gT-mike** [colmap/colmap#390]
Dear Johannes,

I recently checked the output of the depth maps that colmap produces after the dense_stereo step and it appears that these are always slightly smaller than the original images (.e.g if start with 320x240, colmap will give me depthmaps with sizes between 298x222 and 302x226). Is it supposed to be like this or do I use the read_dense.py wrongly?

I extract the depthmaps from the bin files by using the read_dense.py that comes with colmap in the following way:

my_depthmap = read_dense.read_array(my_depthmap_binfile.bin)

len(my_depthmap) is always smaller than the original 320 px of the input image.

Many thanks,
Mike

**Comment by ahojnnes** [comment]
COLMAP undistorts the images before the dense reconstruction stage. If you use different intrinsics for every image, then each undistorted image will have a different output size.

**Comment by gT-mike** [comment]
What do you mean with "different intrinsics"? Is there a way to equalize the intrinsicts or tell the image_undistorter which format (WxH) to use in the end?

Thanks

**Comment by t-fi** [comment]
Camera intrinsics can be shared as described here:
https://colmap.github.io/faq.html#faq-share-intrinsics

also, a summary of available camera models can be found here:
https://colmap.github.io/cameras.html

Assuming one desires depth maps that fit the original images (all from the same camera), the most appropriate model is the pinhole camera. The only free parameter would be the focal length. As COLMAP cannot determine the global world scale, it should be possible to absorb the focal length. So maybe the following options (for `bundle_adjuster`) are enough, so that no camera parameters are estimated at all:

  --BundleAdjustment.refine_focal_length 0
  --BundleAdjustment.refine_principal_point 0
  --BundleAdjustment.refine_extra_params 0

That way we don't need to fiddle with the database. Is that reasonable or am I missing something?

**Comment by ahojnnes** [comment]
@t-fi Described your options correctly. Let us know if you have other questions. Closing this as resolved in the meantime.
