### ISSUE TITLE
Performance Pipeline for fixed cameras

### ISSUE THREAD

**Issue by goetzmoritz** [colmap/colmap#420]
This is more a question than a feature request.

I've constructed a turntable for the scanning purposes of archaeological finds and I actually only need to run the dense mapper on my dataset.

I have a 4 Volta GPU machine with 32 cores and I still struggle finding my best workflow for getting a colored dense point cloud at the end.

Any help for a proper pipeline for that type of task is highly welcome :)

This is how I do it right now:

```
DATASET_PATH=$1
THREADS=32

colmap feature_extractor \
   --database_path $DATASET_PATH/database.db \
   --image_path $DATASET_PATH/images \
   --SiftExtraction.use_gpu 1 \
   --SiftExtraction.gpu_index=0,1,2,3 \
   --SiftExtraction.max_image_size 10000 \
   --SiftExtraction.max_num_features 80000 \
   --ImageReader.single_camera 1

colmap exhaustive_matcher \
   --database_path $DATASET_PATH/database.db \
   --SiftMatching.max_num_matches 100000 \
   --SiftMatching.multiple_models 0 \
   --SiftMatching.use_gpu 1 \
   --SiftMatching.gpu_index 0,1,2,3

mkdir $DATASET_PATH/sparse

colmap mapper \
    --database_path $DATASET_PATH/database.db \
    --image_path $DATASET_PATH/images \
    --export_path $DATASET_PATH/sparse \
    --Mapper.ba_global_use_pba 1 \    
    --Mapper.ba_global_pba_gpu_index 0 \
    --Mapper.num_threads $THREADS \
    --Mapper.multiple_models 0 \
    --Mapper.extract_colors 1 \
    --Mapper.tri_ignore_two_view_tracks 0


colmap image_undistorter \
    --image_path $DATASET_PATH/images \
    --input_path $DATASET_PATH/sparse/0 \
    --output_path $DATASET_PATH/dense \
    --output_type COLMAP \
    --max_image_size 2000

colmap dense_stereo \
    --workspace_path $DATASET_PATH/dense \
    --workspace_format COLMAP \
    --DenseStereo.gpu_index 0,1,2,3 \
    --DenseStereo.geom_consistency true

colmap dense_fuser \
    --workspace_path $DATASET_PATH/dense \
    --workspace_format COLMAP \
    --input_type geometric \
    --output_path $DATASET_PATH/dense/fused.ply

colmap dense_mesher \
    --input_path $DATASET_PATH/dense/fused.ply \
    --output_path $DATASET_PATH/dense/meshed.ply \
    --DenseMeshing.point_weight 1.2 \
    --DenseMeshing.depth 14

```

**Comment by ahojnnes** [comment]
- Depending on the lens distortion of your camera, you might want to use a slightly more complex camera model (e.g., ``--ImageReader.camera_model OPENCV`` or ``--ImageReader.camera_model RADIAL``).
- Since you have Volta GPUs, there shouldn't be a memory problem, so you could set ``--max_image_size 4000`` or higher. At the same time, I suggest to increase the patch size in the stereo step.
- Since you are only interested in the point cloud, there is no need for the final meshing step.
- If you are interested in tuning the pipeline towards your requirements, I suggest to checkout https://colmap.github.io/faq.html

**Comment by goetzmoritz** [comment]
That helped. thanks!
