### ISSUE TITLE
FindTransitiveCorrespondences will find a correspondence on the original reference image

### ISSUE THREAD

**Issue by imkaywu** [colmap/colmap#437]
Hi Dr. Schönberger

I was wondering if there is a bug in the current implementation of `FindTransitiveCorrespondences`: it is highly likely that it will find a correspondence `corr` in the original image (`image_id`), whose point2D identifier is not gonna be the input point2D `point2D_idx`, which means that two distinct points on the same images are considered corresponding points. Does it make sense to implement this way?

**Comment by ahojnnes** [comment]
This is intended, since two keypoints in an image might be located very close together or sometimes exactly coincide, if the coinciding keypoints were detected at different scales. In general, in COLMAP 3D points might be observed multiple times from the same image. However, they must satisfy the maximum reprojection error threshold.
