### ISSUE TITLE
random scenario when multi-thread running "EstimateUncalibrated" function

### ISSUE THREAD

**Issue by hiakru** [colmap/colmap#438]
I found a random scenario when multi-thread running "EstimateUncalibrated" function.
repro step:
1. set fixed seed in util/random.cc

> void SetPRNGSeed(unsigned seed) {
>   // Overwrite existing PRNG
>   if (PRNG != nullptr) {
>     delete PRNG;
>   }
> 
>   if (seed == kRandomPRNGSeed) {
>     /*seed = static_cast<unsigned>(
>         std::chrono::system_clock::now().time_since_epoch().count());*/
>     seed = 99995039;
>   }
> 
>   PRNG = new std::mt19937(seed);
> }
> 
2. 20 multi-thread run EstimateUncalibrated in two_view_geometry.cc
> https://github.com/colmap/colmap/blob/dev/src/estimators/two_view_geometry.cc#L365

it seems no issue with multi-thread, because each pair seperately handled in one thread.
but the inlier number is different for same image pair, after run 2 time.
I'm not sure why? could you help?

Thanks,
Wei

**Comment by ahojnnes** [comment]
Can you try and set the random seed at the beginning of the TwoViewGeometry::EstimateUncalibrated function? It should fix the issue. The reason is that in multi-threaded mode, different threads will process different image pairs in arbitrary order and then the random number generator is in a different state when you run the code multiple times.

**Comment by hiakru** [comment]
Oooh, yes!  should be the problem. Thanks!!!
