### ISSUE TITLE
settings for fisheye camera

### ISSUE THREAD

**Issue by youngzi1004** [colmap/colmap#451]
hi!
I used the images captured by a fisheye camera to creat a mode. The FOV of the camera is 190 degree and images were token in a underground parking lot.  I have tried different camera models, but the result is negative.
I'm guessing that the FOV affects the reconstruction.
Could you give some advice about the settings for the fisheye camera?  
Thanks a lot!

**Comment by robertguetzkow** [comment]
There are different camera models for fisheye lenses available in COLMAP:
- SIMPLE_RADIAL_FISHEYE
- RADIAL_FISHEYE
- OPENCV_FISHEYE

Yes the FOV is relevant for the reconstruction in several ways. You need to make sure that there is a good amount of overlap between the images you're taking and that you're capturing the object from different sides, angles and heights. The FOV is a relevant part of the camera's intrinsic parameters, which describe how the object is projected into 2D when taking a photo. COLMAP will try to estimate the focal length, FOV and distortions coefficients. Unless you know the exact parameters of you camera due to pre-calibrations it's better to let COLMAP figure these out on its own (so instead of using "Custom parameters" during feature extraction, use "Parameters from EXIF" which should be the default).

Are you sure your fisheye lense has 190° FOV? That would be extraordinarily large and nothing I've ever heard of.

**Comment by ahojnnes** [comment]
Thanks @robertguetzkow for your reply.

**Comment by DuVogel87** [comment]
@youngzi1004 
Did you ever solve dual fisheye alignement with colmap?
