### ISSUE TITLE
qt.qpa.plugin issue causing crash

### ISSUE THREAD

**Issue by cpyarger** [colmap/colmap#475]
Windows 10, Tried to run, GUI Crashes and command line gives the following

qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by ahojnnes** [comment]
Did you use the COLMAP.bat script or how did you start the application? Did you set some specific environment variables for Qt that could cause the issue?

**Comment by ahojnnes** [comment]
Closing due to lack of feedback.

**Comment by lawleenaja** [comment]
add the following as an environment variable QT_PLUGIN_PATH  F:\COLMAP\COLMAP-dev-windows-no-cuda\lib (relevant to your colmapinstall\bin directory)

**Comment by DebbyX3** [comment]
Had the same issue

As hinted by @lawleenaja:
I fixed it by creating a new system environment variable called `QT_PLUGIN_PATH`, where the value is the complete path to `Your_colmap_installation_folder\plugin` (e.g.: `C:\Users\your_username\[...]\colmap-x64-windows-nocuda\plugins`)

**Comment by OleGarhZh** [comment]
Problem and solution: "Qt platform plugin"
Problem:
I tried to run automatic 3D tracking using the batch_reconstruct.bat script, but COLMAP kept giving the error qt.qpa.plugin: Could not find the Qt platform plugin "windows". This caused the entire process to crash.

Analysis:
It turned out that the script could not find the necessary .dll files for COLMAP, although the program itself started without problems if I opened it manually.

Solution:
I solved this problem by adding a system environment variable that points to the location of the plugin files.

I opened "Environment Variables" (via search or Windows + R and sysdm.cpl).

In the System Variables section, I created a new variable with the following settings:

Variable Name: QT_QPA_PLATFORM_PLUGIN_PATH

Variable Value: C:\Users\Admin\Desktop\photogrammetry\Automated tracker\01 COLMAP\plugins (this is the path to my plugins folder).

After that, I restarted my computer.

Result:
The Qt platform plugin error is gone and the script now runs COLMAP successfully. This solution helped me overcome the first hurdle. Now I can focus on the quality of my footage so that COLMAP can create a 3D model.
