### ISSUE TITLE
I want to use NDK transplant COLMAP project to Android platform ,can you give me some advice?

### ISSUE THREAD

**Issue by Beannn** [colmap/colmap#52]
as the title says.I have a problem , the glog library can't convert to android, the opengl also.These problems make me very helpless.

**Comment by ahojnnes** [comment]
I don't have experience with Android but since glog is a Google library, it should be possible to compile it on Android. I suggest to consult the Ceres-Solver library for help. I am confident that someone there already compiled Ceres-Solver for Android. Closing this issue, but feel free to reopen the thread. Best, Johannes
