### ISSUE TITLE
Outward looking cameras

### ISSUE THREAD

**Issue by tksharpless** [colmap/colmap#536]
I'm interested in reconstructing panoramic "3D bubbles" from images taken by a spherical array of cameras facing outward from a common center.  The default processing of one such image set gave a sphere of inward-facing  cameras and very poor scene geometry.  Is there a way to get COLMAP to use an outward-facing model?  I could actually provide quite accurate camera poises.

**Comment by ahojnnes** [comment]
Panoramas are difficult to reconstruct, because (euclidean) reconstruction of the scene requires a sufficient baseline between your cameras wrt. the scene. If you have accurate camera poses a priori, you could try to follow the instructions here: https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses

**Comment by tksharpless** [comment]
Thanks, Johannes
I would like to try the dense step only. I could provide both camera poises
and a sparse point cloud.  But there is another problem.
My lenses are Samyang fish eyes with approximately a stereographic
projection function.  Is there a suitable camera model in colmap?
-- Tom
