### ISSUE TITLE
Intrinsic matrix calculating

### ISSUE THREAD

**Issue by JimZhou-001** [colmap/colmap#546]
Hello,

Thank you for providing such a good SfM system.

I find colmap will read EXIF information to calculate the intrinsic matrix. But is it accurate? And during the SfM process, will this matrix be refined? If yes, I want to know how to do that. The intrinsic matrix can be caculated by decomposing the fundamental matrix, right? Dose colmap use this method?

Looking forward to your reply.

Thank you very much!

**Comment by ahojnnes** [comment]
EXIF is only used to extract focal length information. This information is then refined during incremental reconstruction in absolute pose estimation and bundle adjustment. If no prior information is available, I keep the principal point fixed at the image center, because it’s estimation from a single image is an ill posed problem. I don’t use fundamental matrix decomposition to determine the intrinsics, because it is not reliable in my experience (however, I have it implemented somewhere in the code) - it is more robust to do the refinement in incremental reconstruction. The essential matrix is typically also quite robust to changes in the focal length. You can multiply by 0.5 or 2 and still get very similar inliers / relative pose. 

Depending on the chosen camera model, I also estimate lens distortion coefficients, which are estimated in absolute pose estimation / bundle adjustment as well.
