### ISSUE TITLE
Windows debug build completely broken

### ISSUE THREAD

**Issue by chris1248** [colmap/colmap#611]
**Describe the bug**
The build fails in so many places and ways.

**To Reproduce**
1. Checkout a clean repo of this colmap project
build with
--build_type debug
Sit back and watch it fail utterly, in so many places.

**Expected behavior**
It should build

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by ahojnnes** [comment]
Building in debug will be useless anyway, as it runs way to slow. Build it in RelWithDebInfo, if you really want to debug something under Windows. Closing this as there is no intention of making debug builds work under Windows. Debug builds should work under GCC/Clang, but I haven’t tried in along time either.

**Comment by BojianWu** [comment]
@chris1248 I just figured out one way to make it work on Windows 10 (Visual Studio 2015 Version 14.0 Update 3). Please take a look, I hope it could also be helpful for you. ;-)

Basically, I changed some scripts to solve the incompatibility. More details are listed as follows:

1) **cmake/FindGlew.cmake**. On Windows 10, the name of compiled library for GLEW in debug (glew32d.lib) and release (glew32.lib) mode is different. So we should change **FindGlew.cmake**, in order to link the correct complied library for cmake.

2) **scripts/python/build.py**. Similar to the issue mentioned above, after building GLEW, we should move 'glew32d.lib' (debug mode) to the correct destination.

3) **CMakeLists.txt**. In my case, I still need to specify one extra flag (/bigobj) for VS to solve the following compilation error.

>  fatal error (exceeded object file format limit) and the suggestion to compile with the flag /bigobj

Lastly, I used an additional argument (**--without_suite_sparse**) to avoid the error when linking with the complied libraries of ceres-solver in debug mode.

Hope it could help.

Please check my changes attached below, and let me know if you have any other more elegant ways to solve this issue. Thanks!

[colmap-win-debug.zip](https://github.com/colmap/colmap/files/3124637/colmap-win-debug.zip)
