### ISSUE TITLE
Output consistency

### ISSUE THREAD

**Issue by YoussephAhmed** [colmap/colmap#727]
There is a problem regarding repeating the results from the mapper given the same input and by input I mean the same input images, same output of all the steps before the mapper phase including the generated database. I ran the feature extraction and feature matching from the command line, then used the output as input for the mapper step 3 different times with 3 different outputs
First of all why the output is so different and Is there a way to get consistent results given the same output of the feature extraction phase and same input images

**Comment by ahojnnes** [comment]
COLMAP uses various randomized algorithms in the pipeline, which cause undeterministic results.

**Comment by ahojnnes** [comment]
Checkout the latest commits in the dev branch. COLMAP should now be fully deterministic with the default parameters.

**Comment by Tonsty** [comment]
@ahojnnes ，I found when thread num is set to 1 the output of “*_matcher” and “mapper/hierarchical_mapper” will be determinisitc， but when thread num is set larger than 1 or -1 their output may change

**Comment by f-dy** [comment]
+1 even if most of COLMAP is deterministic, Ceres solver (used for bundle adjustment) is not when thread num is more than 1. Refs:
- https://github.com/ceres-solver/ceres-solver/issues/664
- https://groups.google.com/g/ceres-solver/c/F_bbG_5afnY

Even with a single thread, if the problem happens to be poorly conditioned, this may result in a non-deterministic behavior (because of the underlying linear algebra library)
