### ISSUE TITLE
Camera type changes between sparse and dense reconstruction

### ISSUE THREAD

**Issue by KhaledSharif** [colmap/colmap#804]
**Describe the bug**
Camera type changes between sparse and dense reconstruction. I specified that I only have 1 camera and the type is SIMPLE_RADIAL during sparse reconstruction (i.e. by setting ImageReader.single_camera to true and ImageReader.camera_model to SIMPLE_RADIAL during the feature_extractor step). This is true for the sparse model and can be verified by looking at cameras.txt in the sparse folder (sparse/0/cameras.txt). However the dense model does not share the same camera (I can verify this by looking at dense/sparse/cameras.txt) and it uses a PINHOLE camera with different parameters. How can the camera be fixed between the sparse and dense reconstruction steps?

**To Reproduce**
1. Run feature extraction setting ImageReader.single_camera to true and ImageReader.camera_model to SIMPLE_RADIAL.
2. Continue with all steps to produce both sparse and dense reconstructions.
3. Check cameras.txt in both sparse/0/cameras.txt and dense/sparse/cameras.txt.

**Comment by tsattler** [comment]
This is not a bug but intended behavior. Multi-view stereo is easier when the images do not exhibit radial distortion. Thus, Colmap first undistorts the images, producing images that can be described by the pinhole model without distortion. Then, multi-view stereo is performed on these undistorted images rather than the original ones. Note that the camera parameters you find in the dense model have been computed from the parameters of the sparse model as part of the undistortion process.
Note that as part of this process, the size of the images can change.

**Comment by KhaledSharif** [comment]
Thank you for the explanation @tsattler , have a great day! :)
