### ISSUE TITLE
How to calculate the rescale camera parameters?

### ISSUE THREAD

**Issue by Masahiro1002** [colmap/colmap#845]
Hi! I have two questions.
First, are the output camera parameters of txt file and binary file different?
Second, how to calculate the rescale camera parameters and rescale camera width height?

I tried colmap with EuRoC MAV dataset.
https://projects.asl.ethz.ch/datasets/doku.php?id=kmavvisualinertialdatasets

The original image size is 752 * 480.
The output image size is 949 * 518
I used OpenCV format as the camera parameter and input the given camera parameter from the dataset.

[fx, fy, cx, cy]
The input camera parameter is
[458.654000, 457.296000, 367.215000, 248.375000]
The output camera parameter from txt file is 
[4.60580e+02  4.60825e+02  3.67215e+02  2.48375e+02] 
The output camera parameter from bin file is 
[460.58038527867217, 460.82490506583815, 463.4136103723404, 268.03802083333335]

I am not sure how to calculate rescaled fx, fy, width, height.
Thank you!

**Comment by tsattler** [comment]
You can linearly scale the focal length values and the principal point based on the change in  image size. If you have distortion terms, often you do not need to re-scale them since distortion is usually applied before scaling by the focal length. However, you should check this based on the camera model you are using.

The output of the txt and the binary file should be identical (up to loss in writing out a limited number of decimals in the txt case). You can see that the txt output is nearly identical to your input (I assume that you ran the 3D reconstruction without fixing the intrinsic parameters). The focal length values for the binary one also seem identical to me. However, the principal point is different. Per default, Colmap does not optimize for the principal point. Did you allow optimization of the principal point, thus leading to a different 3D model compared to what is stored in the txt file?

**Comment by Masahiro1002** [comment]
Thank you for the response.
I undistorted images before I use colmap and stopped optimizing the principal point. Then, I could get ideal results.
