### ISSUE TITLE
camera model 

### ISSUE THREAD

**Issue by Juuustin** [colmap/colmap#851]
When I run colmap, the output of the camera model is a simple radial camera,my question is:
1. what is the difference between simple radial and pinhole camera model?  
2. is it available to select pinhole as my camera model?  
3. the output of the 3d is like a ball, that is, the ground is not flat, is it possible to fix it?

**Comment by tsattler** [comment]
For 1 and 2: Did you have a look at the Colmap documentation, especially https://colmap.github.io/cameras.html ?

3 might be an artifact of estimating the radial distortion inside of Colmap (in this case, pre-calibrating the camera would help), due to a critical configuration (e.g., http://ccwu.me/file/radial.pdf), or an unstable configuration (either not enough baseline compared to the depth of the scene). Impossible to tell from afar without looking at the data.

**Comment by Juuustin** [comment]
> For 1 and 2: Did you have a look at the Colmap documentation, especially https://colmap.github.io/cameras.html ?
> 
> 3 might be an artifact of estimating the radial distortion inside of Colmap (in this case, pre-calibrating the camera would help), due to a critical configuration (e.g., http://ccwu.me/file/radial.pdf), or an unstable configuration (either not enough baseline compared to the depth of the scene). Impossible to tell from afar without looking at the data.

I read through the document about the camera model but didn't understand it clearly. 
Could we select the camera model before we start to reconstrust? for example, it is advised to try different camera models in the doc, but I didn't find an option to switch between different models.

**Comment by tsattler** [comment]
Yes, you can choose the camera model, both from the gui and from the command line.
See https://colmap.github.io/tutorial.html#feature-detection-and-extraction and https://colmap.github.io/cli.html

**Comment by Juuustin** [comment]
> Yes, you can choose the camera model, both from the gui and from the command line.
> See https://colmap.github.io/tutorial.html#feature-detection-and-extraction and https://colmap.github.io/cli.html
Great! I only use the automatic reconstruction, now I know how to do it.
Thank you very much :)
