### ISSUE TITLE
Some question on sparse reconstruction for a video capture from practical environment

### ISSUE THREAD

**Issue by waitingjiang** [colmap/colmap#895]
First, thanks for sharing such a great work! 

I am currently using COLMAP to do sparse reconstruction for a video captured from Office scene, while after reconstruction, it always generated several sub-models which, I guess, probably caused by image registration failure.  The result expected is a well-build only one model, which will be further used in [HFnet ](https://github.com/ethz-asl/hfnet) for visual place re-localization. below is some information for my dataset and command line used.

1. I installed my camera on mobile robot platform Kobuki,  control the movement and captured the video, the movement is almost constant forward, or coupling with angular and  linear velocity, sure with no pure rotation.  
2. for one video, there almost are 6000 images, after resample, with 1500 images left.
3. I used the following command line for sparse reconstruction

- feature_extractor: colmap feature_extractor --database_path 05_22_02_3d_result/database.db --image_path images/ --ImageReader.single_camera=1 --ImageReader.camera_model=OPENCV_FISHEYE  --SiftExtraction.gpu_index=0

- feature_matching: colmap sequential_matcher --database_path 05_22_02_3d_result/database.db --SiftMatching.gpu_index=0

- sparse reconstruction: colmap mapper --database_path 05_22_02_3d_result/database.db --image_path images/ --output_path 05_22_02_3d_result/sparse

I have some questions on the process. 
**firstly**, cuz all the images comes from one camera, and I've already calibrated the camera, so is it necessary for me to give the camera_params and fix the value?
**secondly**, are there any other settings to avoid the image registration failure ? 
**thirdly**, I am not sure the command line is the best way to do sparse reconstruction, could you give me some suggestion on how to generate one model. 

Very much appreciated for your help!

**Comment by hiakru** [comment]
For your first question, better give an init camera params, such as :
v_ImageReader_camera_model="RADIAL";
v_ImageReader_camera_params="1156.235278,427.125929,586.273878,-0.377801,0.240173";

For second/third, as far as I know, the model splits mostly directly caused by could not find another image to do registration. There are many reasons, such as inlier nums, register trials threshold etc.

According to my usage, the most important is inlier num, better check before run mapper.
For matching step , there are many configurable params, such as:
![image](https://user-images.githubusercontent.com/33151098/84620272-209e4b00-af0a-11ea-882a-006d4cc7f1f4.png)
mapper step has many params too.

Hope this could help!

**Comment by waitingjiang** [comment]
thanks for your reply! 

I found several models comes from illumination change for office scene. When  re-captured the video with no strong illumination changes, the problem got solved. 

Thank you very much for the kind suggestion.
I will close the issue.
