### ISSUE TITLE
Depth divide in fusion

### ISSUE THREAD

**Issue by maorp** [colmap/colmap#911]
Hi. A question about fusion.cpp -
I dont understand the depth divide on line 342.  The depth error gets normalized and does not corresponds to real units. just wanted to make sure its intended...
// Depth error of reference depth with current depth.
      const float depth_error = std::abs((proj(2) - depth) / depth);
      if (depth_error > options_.max_depth_error) {
        continue;
      }

**Comment by tsattler** [comment]
3D reconstruction from images are only defined up to an arbitrary scaling factor, i.e., it is unclear whether one unit is cm, m, km, ... This is because it is not possible to recover the size of the reconstructed scene only from images (some additional information is needed). It thus makes no sense to threshold the absolute depth error. Instead, it is normalized, which allows defining a single threshold for all reconstructions.

**Comment by maorp** [comment]
Thats clear. Thanks!
