### ISSUE TITLE
Noisy Surface normal estimation from MVS

### ISSUE THREAD

**Issue by lixx2938** [colmap/colmap#97]
Hi,

I tried to densely reconstruct multiple models from internet photos using MVS. most of depth estimates are pretty good to me. However, at least half of normal estimates are super noisy if I use colmap matlab script to visualize them.  Is it the problem of algorithm itself or something else?

**Comment by ahojnnes** [comment]
Can you show an example please?

**Comment by lixx2938** [comment]
Two noisy surface normal examples of Colosseum are below. Note that I used 4 +5 iterations of MVS which is the same as colmap documentation and depth maps are pretty good to me. 

![1](https://cloud.githubusercontent.com/assets/7671455/24667098/2af4361e-1930-11e7-9d58-a53a4313aa93.jpg)

![2](https://cloud.githubusercontent.com/assets/7671455/24667102/31929056-1930-11e7-8cfb-acd022a06047.jpg)

**Comment by ahojnnes** [comment]
I think, those depth maps do not look bad, considering that they are produced from internet images with rather low resolution it seems. Normal estimation benefits from high resolution and a large window radius. If you want more reliable (and smoother) normal maps, try increasing the ``--DenseMapperOptions.patch_match_window_radius`` option to a larger value and/or using higher resolution input images.

**Comment by ahojnnes** [comment]
Closing this issue for now as resolved, feel free to reopen in case you have more questions.

**Comment by robin-gdwl** [comment]
I know this Issue is closed, just adding a bit of Information for others that might find this thread.

Had a similar Problem with noisy depthmaps and normalmaps. 
A larger patch_match_window_radius significantly improved the results. 

Left side: Photometric Depthmap with a radius of 5 
RIght side: Photometric Depthmap with a radius of 10, all other parameters being equal. 

![image](https://user-images.githubusercontent.com/25942644/103465461-f2644980-4d3b-11eb-8f98-fe6169a623bb.png)

I am currently investigating how to further improve depth map quality.
